# Generated by Django 5.0.4 on 2024-06-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSensorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CropType', models.IntegerField()),
                ('CropDays', models.IntegerField()),
                ('SoilMoisture', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Temperature', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Humidity', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
