# Generated by Django 5.0.4 on 2024-06-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationsensorsmodel',
            name='Humidity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='irrigationsensorsmodel',
            name='SoilMoisture',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='irrigationsensorsmodel',
            name='Temperature',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
