# Generated by Django 5.0.4 on 2024-06-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Phosphorus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Potassium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Rainfall', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
